[11.0] add module web_search_date_range
Numigi/odoo-web-addons pull request #8
Opened 2018-05-18 20:15 UTC by ddufresne

https://isidor-prod.numigi.net/web#id=1762&view_type=form&model=project.task&action=292&active_id=108&menu_id=200

2018-05-21 02:07 UTC, foutoucour requested changes
Il faudrait revoir l'architecture du test.

2018-05-21 02:07 UTC, foutoucour commented on web_search_date_range/tests/test_search_date_range.py
> +class TestSearchDateRange(common.SavepointCase):
le code peut être grandement réduit si on utilise du ddt je pense:
regarde ce qui a été fait ici: https://github.com/Numigi/ansible_odoo_instance/blob/master/tests/test_instance_setup.py#L16
Il faudrait utiliser [ddt](http://ddt.readthedocs.io/en/latest/example.html) pour garder l'utilisation de `SavepointCase`

2018-05-22 00:49 UTC, ddufresne commented
@foutoucour fixed

2018-05-22 20:20 UTC, ddufresne commented
@foutoucour est-ce que ça te convient comme suite de tests ?

2018-05-22 20:29 UTC, foutoucour approved these changes

2018-05-22 21:52 UTC, merged